void escolhaMenuAlgoritmos();
void escolhaMenuElementos();
int *alocacaoVetor(int extensaoVetor);
double *armazenaTempo();
int escolheValor(int escolhaElementos);
double medicaoDeTempo(int escolhaAlgoritmo, int escolhaElementos);
void mergeSort(int *v, int inicio, int fim);
void merge(int *v, int inicio, int meio, int fim);
void medicaoDeTempoMelhorPiorCaso(int escolhaAlgoritmo, int escolhaElementos);
int particiona(int *V, int inicio, int final );
void quickSort(int *V, int inicio, int fim);
int* countingSort(int array[], int tamanho);
void timSort(int *v, int n);
int minRunLength(int n);
void insertionSortTim(int *v, int left, int right);
void shellsort(int *vetor, int tamanho);
void bubbleSort(int *vetor, int tamanho);
void selectionSort(int *vetor, int tamanho);
void heapify(int *vetor, int tamanho, int i);
void heapSort(int *vetor, int tamanho);
void insertionSort(int *v, int n);
void radixSort(int *arr, int n);
void radixSort(int *arr, int n);
int getMax(int *arr, int n);
char* nomeAlgoritmo(int escolhaAlgoritmo);
